### ISSUE TITLE
fix `npm install -g ferment` version mismatch error

### ISSUE THREAD

**Issue by mmckegg** [fermentation/ferment#5]
For some reason #2 hasn't fixed `npm install -g ferment`.

@ahdinosaur @mixmix Any ideas how to solve this?

**Comment by mmckegg** [comment]
@ungoldman Just tried using `postinstall` but while it runs, doesn't actually seem to be triggering a rebuild. You still get the error. 

This probably would have worked with the old nested node_modules, but I suspect is having trouble with the flat structure.

**Comment by arj03** [comment]
I can confirm that the 0.2.2 rebuild option works :)

**Comment by mmckegg** [comment]
Awesome, that's great! Thanks letting me know 😅

**Comment by Marak** [comment]
Closing. 

Most likely was issue with `npm` cache / older versions of `npm`.

If anyone hits this issue again please make sure to update `npm` CLI to the latest version and try running `npm cache clean`
