### ISSUE TITLE
Check out Soundstorm for a way better project

### ISSUE THREAD

**Issue by tubbo** [fermentation/ferment#70]
This project is shit and the developer is a garbage person. Check out my project Soundstorm, it does the same thing but actually works and isn't made by a trash person.

https://github.com/weathermen/soundstorm

**Comment by celesteh** [comment]
I'd be interested in a similar project doing similar work, but I'm really put off by this wording. Ceasing development on a project doesn't make somebody a "garbage person." What the hell, dude?

**Comment by tubbo** [comment]
> Ceasing development on a project doesn't make somebody a "garbage person."

@celesteh no, but making bombs in your own house and being a terrorist certainly does.

- https://github.com/fermentation/ferment/graphs/contributors
- https://abc7ny.com/suspicious-package-queens-astoria-fire/6425363/

**Comment by celesteh** [comment]
Ok, that is bad. It looks like he only made like 12 commits though?  It seems like the vast majoriy of the work on this was done by Australians.
